-- ST-2a (#293) — rename every *Wei money column to *Stroops.
--
-- This is a pure column RENAME, not a drop/recreate: the type stays BigInt and
-- every existing value is preserved in place. Prisma's autogenerated migration
-- would emit DROP COLUMN + ADD COLUMN (data loss) because it cannot infer a
-- rename, so this migration is hand-written. The wei->stroops *scale* change
-- (18 -> 7 decimals) is a value-layer concern handled in ST-2b (#294), not here.
--
-- ASSUMPTION: a fresh, Celo-free database. Because this is a byte-for-byte
-- RENAME, any pre-existing Celo-era row keeps its 18-decimal wei value while now
-- living in a *Stroops column — off by 10^11 (1 cUSD = 1e18 wei vs 1 XLM = 1e7
-- stroops). The `stellar` branch targets a fresh DB with no Celo production
-- history, so no value conversion is performed here. If this is ever run against
-- a DB holding real Celo-era rows, a data-conversion step (… / 100000000000) per
-- renamed column must run before/alongside this migration.

-- users
ALTER TABLE "users" RENAME COLUMN "totalEarnedWei" TO "totalEarnedStroops";
ALTER TABLE "users" RENAME COLUMN "pendingBalanceWei" TO "pendingBalanceStroops";

-- tasks
ALTER TABLE "tasks" RENAME COLUMN "rewardWei" TO "rewardStroops";

-- campaigns
ALTER TABLE "campaigns" RENAME COLUMN "rewardWei" TO "rewardStroops";

-- submissions
ALTER TABLE "submissions" RENAME COLUMN "payoutAmountWei" TO "payoutAmountStroops";

-- payout_jobs
ALTER TABLE "payout_jobs" RENAME COLUMN "amountWei" TO "amountStroops";

-- balance_ledger
ALTER TABLE "balance_ledger" RENAME COLUMN "amountWei" TO "amountStroops";

-- user_balance_ledger
ALTER TABLE "user_balance_ledger" RENAME COLUMN "amountWei" TO "amountStroops";

-- campaign_balances
ALTER TABLE "campaign_balances" RENAME COLUMN "balanceWei" TO "balanceStroops";

-- flagged_withdrawals
ALTER TABLE "flagged_withdrawals" RENAME COLUMN "balanceWei" TO "balanceStroops";
