import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const workflow = readFileSync(
  resolve(process.cwd(), ".github/workflows/single-contributor.yml"),
  "utf8",
);

describe("single-contributor pull request workflow", () => {
  it("checks every opened or updated pull request", () => {
    expect(workflow).toMatch(
      /^on:\n  pull_request_target:\n    types: \[opened, synchronize, reopened, edited\]/m,
    );
    expect(workflow).toContain("github.rest.pulls.listCommits");
    expect(workflow).toContain("github.paginate(");
    expect(workflow).not.toContain("actions/checkout");
  });

  it("cancels stale checks for the same pull request", () => {
    expect(workflow).toContain(
      "group: single-contributor-${{ github.event.pull_request.number }}",
    );
    expect(workflow).toContain("cancel-in-progress: true");
  });

  it("requires the exact author and committer identity", () => {
    expect(workflow).toContain('name: "cemmacabales"');
    expect(workflow).toContain(
      'email: "carlmacabales31@gmail.com"',
    );
    expect(workflow).toContain("commit.author?.name");
    expect(workflow).toContain("commit.author?.email");
    expect(workflow).toContain("commit.committer?.name");
    expect(workflow).toContain("commit.committer?.email");
    expect(workflow).toContain("core.setFailed(");
  });

  it("rejects co-author trailers and explicit AI attribution", () => {
    expect(workflow).toContain("commit.message");
    expect(workflow).toContain("context.payload.pull_request.title");
    expect(workflow).toContain("context.payload.pull_request.body");

    const regexSource = workflow.match(
      /const prohibitedAttribution =\n\s+\/(.+)\/i;/,
    )?.[1];
    expect(regexSource).toBeDefined();

    const prohibitedAttribution = new RegExp(regexSource!, "i");
    for (const text of [
      "Co-authored-by: Someone Else <other@example.com>",
      "Generated by OpenAI",
      "Generated-with Claude",
      "Generated-by: Codex",
      "generated-by-AI",
      "Authored by ChatGPT",
      "Authored-by: Codex",
    ]) {
      expect(prohibitedAttribution.test(text), text).toBe(true);
    }

    expect(prohibitedAttribution.test("Implement Codex issue dispatch")).toBe(
      false,
    );
  });

  it("uses read-only repository access plus narrowly scoped status writes", () => {
    expect(workflow).toMatch(
      /permissions:\n  contents: read\n  pull-requests: read\n  statuses: write/,
    );
  });

  it("publishes the required status on the pull request head commit", () => {
    expect(workflow).toContain("context.payload.pull_request.head.sha");
    expect(workflow).toContain("github.rest.repos.createCommitStatus");
    expect(workflow).toContain('context: "single-contributor/verified"');
    expect(workflow).toContain('await publishStatus("pending"');
    expect(workflow).toContain('? "failure" : "success"');
  });
});
